model:
  target_sequence_length: 1  # Predicting the next closing price
  huber_delta: 2.516163107358062  # Delta for Huber loss, can be adjusted based on the dataset
  # non-normalized weighted averaging of CNN and ElasticNet regression outputs #
  
  price_loss_weight: 0.522553591966669
  direction_loss_weight: 0.7843898503992107
  orthogonal_lambda: 0.17775825546595142
  focal_alpha: 0.6078464280406355 # Alpha parameter for Focal Loss, can be adjusted based on class imbalance
  focal_gamma: 4.519494240423438  # Gamma parameter for Focal Loss, can be adjusted based on class imbalance
  focal_beta: 0.999  # Beta parameter for Focal Loss, can be adjusted based on class imbalance
  # Direction threshold is set during feature engineering.

  use_meta_learning: true  # Enable/disable meta-learning
  include_base_losses: true  # Include base model losses in training
  meta_price_loss_weight:  0.5017565395318231
  meta_direction_loss_weight: 1.224786001971306

  price_cnn_weight: 0.6079509612866073
  direction_cnn_weight: 0.27332771706500925
  lstm_weight: 1.2333934401222826
  ridge_weight: 1.449885211852526

  cnnPath: models/cnn_model.pth
  lstmPath: models/lstm_model.pth
  ridgePath: models/ridge_model.pth
  meta_price_path: models/meta_price_model.pth
  meta_direction_path: models/meta_direction_model.pth

cnn:
  inputChannels: 96  # Number of features (RSI, MACD, etc.)
  cnnChannels: [16, 48, 128]  # Reduced capacity to prevent overfitting
  kernelSize: [2, 5, 5]
  poolSize: [2, 3, 2]  # Pooling after each CNN layer
  poolPadding: [0, 0, 0]
  padding: [1, 2, 3]  # kernel_size // 2 for each dimension
  stride: 2
  dropout: [0.4852957761235601, 0.20559207295165977]
  outputSize: 1
  num_classes: 3

Ridge:
  alpha: 0.0021123795371517087  # Regularization strength for Ridge regression, can be adjusted based on the dataset
  fit_intercept: True
  eps: 4.0921764319313715e-07

LSTM:
  hidden_size: 128
  num_layers: 2
  dropout: 0.3

optimiser:
  name: 'adam'
  base_lr: 1.1184368921509642e-05
  meta_lr: 0.0025091223135881133
  weightDecay: 0.002987983775143476  # L2 regularization term 
  eps: 1.2526334356750563e-10
  amsgrad: False  # Whether to use AMSGrad variant of Adam
  schedulerMode: 'min'
  schedulerFactor: 0.17951652539957985
  schedulerPatience: 15
  schedulerMinLR: 4.0880471836742325e-09
