model:
  target_sequence_length: 1  # Predicting the next closing price
  huber_delta: 0.579797487582631  # Delta for Huber loss, can be adjusted based on the dataset
  # non-normalized weighted averaging of CNN and ElasticNet regression outputs #
  cnnWeight: 0.07969888681024252
  elasticNetWeight: 0.9275966383353601
  cnnPath: models/cnn_model.pth
  elasticNetPath: models/elastic_net_model.pth

  
cnn:
  inputChannels: 95  # Number of features (RSI, MACD, etc.)
  cnnChannels: [32, 64, 32]  # Reduced capacity to prevent overfitting
  kernelSize: [3, 3, 2]
  poolSize: [2, 2, 3]  # Pooling after each CNN layer
  poolPadding: [1, 1, 1]
  padding: [1, 1, 1]  # kernel_size // 2 for each dimension
  stride: 1
  dropout: [0.3, 0.5]
  outputSize: 1

ElasticNet:
  alpha: 4.107946250476794  # Regularization strength for ElasticNet, can be adjusted based on the dataset
  l1_ratio: 0.6187360071571415  # Mix ratio between L1 and L2 regularization
  fit_intercept: True
  tol: 6.581686807105016e-05  # Tolerance for stopping criteria
  max_iter: 1000  # Maximum number of iterations
  eps: 1.3516727693360534e-09

optimiser:
  name: 'adam'
  lr: 6.0455189496240446e-05
  weightDecay: 0.000529539419332929  # L2 regularization term 
  eps: 1e-08 
  amsgrad: False  # Whether to use AMSGrad variant of Adam
  schedulerMode: 'min'
  schedulerFactor: 0.5182833306194576
  schedulerPatience: 15
  schedulerMinLR: 1e-7 