model:
  target_sequence_length: 1  # Predicting the next closing price
  huber_delta: 0.579797487582631  # Delta for Huber loss, can be adjusted based on the dataset
  # non-normalized weighted averaging of CNN and ElasticNet regression outputs #
  
  price_loss_weight: 0.5
  direction_loss_weight: 0.5
  direction_threshold: 0.5

  price_cnn_weight: 0.07969888681024252
  direction_cnn_weight: 0.57969888681024252
  elasticNet_weight: 0.8275966383353601
  ridge_weight: 0.9923011131897575
  
  price_cnnPath: models/price_cnn_model.pth
  direction_cnnPath: models/direction_cnn_model.pth
  elasticNetPath: models/elastic_net_model.pth
  ridgePath: models/ridge_model.pth

cnn:
  inputChannels: 96  # Number of features (RSI, MACD, etc.)
  cnnChannels: [32, 64, 32]  # Reduced capacity to prevent overfitting
  kernelSize: [3, 3, 2]
  poolSize: [2, 2, 3]  # Pooling after each CNN layer
  poolPadding: [1, 1, 1]
  padding: [1, 1, 1]  # kernel_size // 2 for each dimension
  stride: 1
  dropout: [0.3, 0.5]
  outputSize: 1
  num_classes: 3

Ridge:
  alpha: 0.1996926370318278  # Regularization strength for Ridge regression, can be adjusted based on the dataset
  fit_intercept: True
  eps: 1e-8

ElasticNet:
  alpha: 4.107946250476794  # Regularization strength for ElasticNet, can be adjusted based on the dataset
  l1_ratio: 0.6187360071571415  # Mix ratio between L1 and L2 regularization
  fit_intercept: True
  tol: 6.581686807105016e-05  # Tolerance for stopping criteria
  max_iter: 1000  # Maximum number of iterations
  eps: 1.3516727693360534e-09

optimiser:
  name: 'adam'
  lr: 6.0455189496240446e-05
  weightDecay: 0.000529539419332929  # L2 regularization term 
  eps: 1e-08 
  amsgrad: False  # Whether to use AMSGrad variant of Adam
  schedulerMode: 'min'
  schedulerFactor: 0.5182833306194576
  schedulerPatience: 15
  schedulerMinLR: 1e-7 