model:
  target_sequence_length: 1  # Predicting the next closing price
  huber_delta: 0.4968892123599037  # Delta for Huber loss, can be adjusted based on the dataset
  # non-normalized weighted averaging of CNN and ElasticNet regression outputs #
  cnnWeight: 0.10762699236155496
  elasticNetWeight: 0.8752708635996657
  cnnPath: models/cnn_model.pth
  elasticNetPath: models/elastic_net_model.pth

  
cnn:
  inputChannels: 95  # Number of features (RSI, MACD, etc.)
  cnnChannels: [32, 64, 128]  # Reduced capacity to prevent overfitting
  kernelSize: [5, 3, 2]
  poolSize: [2, 3, 2]  # Pooling after each CNN layer
  poolPadding: [1, 1, 1]
  padding: [1, 1, 1]  # kernel_size // 2 for each dimension
  stride: 1
  dropout: [0.3, 0.5]
  outputSize: 1

ElasticNet:
  alpha: 0.1996926370318278  # Regularization strength for ElasticNet, can be adjusted based on the dataset
  l1_ratio: 0.5  # Mix ratio between L1 and L2 regularization
  fit_intercept: True
  tol: 1e-4  # Tolerance for stopping criteria
  max_iter: 1000  # Maximum number of iterations
  eps: 1e-6

optimiser:
  name: 'adam'
  lr: 5.157286446775219e-05
  weightDecay: 7.964762599230672e-07  # L2 regularization term 
  eps: 1e-08 
  amsgrad: False  # Whether to use AMSGrad variant of Adam
  schedulerMode: 'min'
  schedulerFactor: 0.6799866718861333
  schedulerPatience: 15
  schedulerMinLR: 1e-7 