data_loader:
  TICKER: "NVDA"
  START_DATE: "2019-01-01"
  END_DATE: "2024-12-31"
  raw_data_path: nocturne_bloom/NVDA_stock_predictor/data/raw/nvda_raw_data.csv
  validation_split: 0.2
  shuffle: true
