data_loader:
  TICKER: "NVDA"
  START_DATE: "2019-01-01"
  END_DATE: "2024-12-31"
  raw_data_path: data/raw/nvda_raw_data.csv  # Path relative to NVDA_stock_predictor folder
  validation_split: 0.2
  shuffle: true
