data_module:
  window_size: 10
  target_col: Close
  x_save_path: data/processed/nvda_processed_x.pt
  y_save_path: data/processed/nvda_processed_y.pt
  batch_size: 64
  num_workers: 7
  train_val_split: 0.8

data_processor:
  x_load_path: ../data/processed/nvda_processed_data.npy
  y_load_path: ../data/processed/nvda_processed_target.npy
  x_save_path: ../data/processed/nvda_processed_x.pt
  y_save_path: ../data/processed/nvda_processed_y.pt
  preprocessing_data_path: data/preprocessing/nvda_processed_data.csv