data_loader:
  raw_data_path: data/raw/nvda_raw_data.csv

features:
  include_past_days: 30
  processed_data_path: data/processed/nvda_processed_data.csv
  SCALER_PATH: models/scaler.pkl
  normalize: true
  scaler_type: minmax  # could be 'standard' or 'robust' too