data_loader:
  raw_data_path: data/raw/nvda_raw_data.csv

features:
  include_past_days: 30
  preprocessing_data_path: data/preprocessing/nvda_processed_data.csv
  SCALER_PATH: models/scaler.pkl
  normalize: true
  scaler_type: minmax
  indicator_cols: 
    - RSI
    - MACD
    - MACDSignal
    - BBHigh
    - BBLow
    - SMA_20
    - EMA_12
    - EMA_26
    - priceChange
    - closeChangePercentage
    - rateOfChange
    - Momentum
    - averageTrueRange
    - rollingStd
    - volumeChange
    - volumeRateOfChange
    - onBalanceVolume
    - Body
    - upperWick
    - lowerWick
