CNNEncoder:
  input_channels: 40  # Number of features (RSI, MACD, etc.)
  CNN_channels: [64, 128, 64]  # Increased capacity
  kernel_size: [3, 3, 2]
  pool_size: [2, 2, 1]  # Pooling after each CNN layer
  pool_padding: [0,0,0]
  padding: [1, 1, 1]  # kernel_size // 2 for each dimension
  stride: 1
  dropout: 0.2  # Added dropout for regularization

LSTMPredictor:
  input_size: 64  # Output size of CNNEncoder (CNN_channels[1])
  hidden_size: 128  # Increased capacity
  num_layers: 3    # Deeper LSTM
  dropout: 0.3
  bidirectional: false
  output_size: 1
  batch_first: true

model:
  target_sequence_length: 1  # Predicting the next closing price