CNNEncoder:
  input_channels: 40  # Number of features (RSI, MACD, etc.)
  CNN_channels: [64, 128]  # Increased capacity
  kernel_size: [2, 3]
  padding: [1, 1]  # kernel_size // 2 for each dimension
  stride: 2

LSTMPredictor:
  input_size: 128  # Output size of CNNEncoder (CNN_channels[1])
  hidden_size: 128  # Increased capacity
  num_layers: 2    # Deeper LSTM
  dropout: 0.2
  bidirectional: false
  output_size: 1
  batch_first: true