model:
  target_sequence_length: 1  # Predicting the next closing price
  huber_delta: 0.4968892123599037  # Delta for Huber loss, can be adjusted based on the dataset
  # non-normalized weighted averaging of CNN and Ridge regression outputs #
  cnnWeight: 0.10762699236155496
  ridgeWeight: 0.8752708635996657
  cnnPath: models/cnn_model.pth
  ridgePath: models/ridge_model.pth


cnn:
  inputChannels: 95  # Number of features (RSI, MACD, etc.)
  cnnChannels: [32, 64, 128]  # Reduced capacity to prevent overfitting
  kernelSize: [5, 3, 2]
  poolSize: [2, 3, 2]  # Pooling after each CNN layer
  poolPadding: [1, 1, 1]
  padding: [1, 1, 1]  # kernel_size // 2 for each dimension
  stride: 1
  dropout: [0.3, 0.5]
  outputSize: 1

Ridge:
  alpha: 0.1996926370318278  # Regularization strength for Ridge regression, can be adjusted based on the dataset

classifiers:
  numEstimators: 100
  learningRate: 2.5093821312798074e-05
  maxDepth: 10
  minSamplesSplit: 5
  minSamplesLeaf: 10
  subSample: 0.5155378717861159
  randomState: 42
  maxFeatures: 'sqrt'
  classWeight: 'balanced'
  C: 5
  solver: 'liblinear'
  maxIterations: 500
  kernel: 'rbf'
  probability: True
  verbose: 0
  MAXEPOCHS: 1

  GBWEIGHT: 0.27053738995027
  RFWEIGHT: 0.3019947415106128
  LOGISTICWEIGHT: 0.13929721635149966
  SVMWEIGHT: 0.28089454454114704

optimiser:
  name: 'adam'
  lr: 5.157286446775219e-05
  weightDecay: 7.964762599230672e-07  # L2 regularization term 
  eps: 1e-08 
  amsgrad: False  # Whether to use AMSGrad variant of Adam
  schedulerMode: 'min'
  schedulerFactor: 0.6799866718861333
  schedulerPatience: 15
  schedulerMinLR: 1e-7 