defaults:
  - _self_
  - model_Ensemble
  - data_module

trainer:
  project_name: "NVDA Stock Predictor - Optimized"
  run_name: "CNN-Ridge Regression"
  max_epochs: 100  # More epochs with early stopping
  accelerator: "auto"
  devices: 1
  log_every_n_steps: 10  # Optimized logging frequency
  seed: 42  # Optimized seed for reproducibility
  gradient_clip_val: 1.8202465970147184  # Gradient clipping to prevent exploding gradients
  early_stopping_patience: 20  # Stop if no improvement for 20 epochs
  early_stopping_delta: 0.0026555012766915995  # Optimized delta for early stopping