defaults:
  - _self_
  - model_CNNLSTM
  - data_module

trainer:
  project_name: "NVDA Stock Predictor"
  run_name: "CNN-LSTM"
  max_epochs: 200
  accelerator: "auto"
  devices: 1
  log_every_n_steps: 10
  seed: 1
  early_stopping_patience: 20  # Stop if no improvement for 20 epochs
  early_stopping_delta: 0.001  # Minimum change to qualify as improvement

optimizer:
  lr: 0.0005  # Slightly higher learning rate to escape local minima
  weight_decay: 1e-4  # Increased regularization